# syntax=docker/dockerfile:1.7@sha256:a57df69d0ea827fb7266491f2813635de6f17269be881f696fbfdf2d83dda33e
FROM node@sha256:16e22a550f3863206a3f701448c45f7912c6896a62de43add43bb9c86130c3e2

WORKDIR /formal
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts
COPY fixtures ./fixtures
COPY lib ./lib
COPY orchestrator ./orchestrator
COPY specs ./specs

ENV NODE_ENV=production
CMD ["node", "specs/run.mjs"]
